version: '2'

services:
  mongodb:
    image: mongo:4.1.8
    hostname: ofriends
    ports:
      - "27017:27017"
    volumes:
      # You can replace /opt/data/mongo_home by any path to
      # a directory on your machine.
      # MongoDB will use that directory to store all the data.
      - /opt/data/mongo_home:/data/db
    restart: always
    networks:
      - elk
    command: ["mongod"]
  backend:
    image: lnquy/realize:2.0.2
    hostname: search-backend
    ports:
      - "8080:8080"
      - "8082:8082"
    environment:
      - ELASTICADDR=http://elasticsearch:9200
      - MONGOADDR=mongodb:27017
    networks:
      - elk
    command: [ "start" ]
    volumes:
        # Add Go packages here if needed
        - ../../../.realize.yaml:/go/src/github.com/PhamDuyKhang/littledetective/.realize.yaml
        - ../../../main.go:/go/src/github.com/PhamDuyKhang/littledetective/main.go
        - ../../../internal:/go/src/github.com/PhamDuyKhang/littledetective/internal/
        - ../../../vendor:/go/src/github.com/PhamDuyKhang/littledetective/vendor/
    working_dir: /go/src/github.com/PhamDuyKhang/littledetective
    depends_on:
      - mongodb
      - elasticsearch
    restart: always

  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5000:5000"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch
  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:
  elk:
    driver: bridge
